# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- script: |
    npm install
    npm install -g pug-cli
  displayName: 'Install NPM modules'

- script: pug src/templates --out ./src/views
  displayName: 'Build PUG templates'

- script: npm run pack
  displayName: 'Package app with electron-build'